version: '3.8'

services:
    php:
        build:
            context: ./build/php
        restart: 'no'
        profiles: ['console']
        volumes:
            - '..:/app:ro'
            - '../local:/app/local'
        working_dir: '/app'
        environment:
            XDEBUG_MODE: 'coverage'
